sudo: false

language: go

go:
  - 1.4
  - tip

install: make updatedeps

script:
  - go test ./...
  #- go test -race ./...

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
