sudo: required

services:
  - docker

language: generic

# establish environment variables
env:
  - TEST_DIR=examples/azure-vm-simple-linux

branches:
  only:
  - /^(?i:topic)-.*$/

# install terraform
before_deploy: cd $TEST_DIR && ./before_deploy.sh

# terraform deploy script
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      repo: 10thmagnitude/terraform
      branch: topic-101-vm-simple-linux

# destroy resources with Azure CLI
after_deploy: ./after_deploy.sh
