####################################################################################
## NOT FOR UPSTREAM PROPOSAL; INTENDED FOR CI OF AZURE EXAMPLES IN THIS REPO ONLY ##
####################################################################################

sudo: required

services:
  - docker

language: generic

env:
  - TEST_DIR=examples/azure-vm-simple-linux

branches:
  only:
  - master
  - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)

# terraform deploy script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./deploy.sh
    on:
      repo: harijayms/terraform
      branch: master

# destroy resources with Azure CLI
after_deploy: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./after_deploy.sh
