sudo: required

services:
  - docker

language: generic

# establish environment variables
env:
  - TEST_DIR=examples/azure-vm-simple-linux

branches:
  only:
  - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)

# terraform deploy script
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      repo: 10thmagnitude/terraform
      branch: topic-101-vm-simple-linux

# destroy resources with Azure CLI
after_deploy: ./after_deploy.sh
