sudo: required

services:
  - docker

language: generic

# establish environment variables
env:
  - TEST_DIR=examples/azure-vm-simple-linux

branches:
  only:
  - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - cd $TEST_DIR && ./before_deploy.sh

# terraform deploy script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TEST_DIR && ./deploy.sh

# destroy resources with Azure CLI
after_deploy:
  - cd $TEST_DIR && ./after_deploy.sh
