language: generic

# establish environment variables
env:
  - TEST_DIR=examples/101-vm-simple-linux

branches:
  only:
  - master
  - /^(?i:topic)-.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TEST_DIR && "./deploy.sh"
    on:
      repo: 10thmagnitude/terraform
      branch: 101-vm-simple-linux
      condition: false  # re-enable when examples exist in master
