name: Test AI Command

on:
  push:
    branches: [ main ]
    paths:
      - 'cmd/tofu/ai.go'
      - 'internal/ai/**'
      - 'test-ai-command.sh'
  pull_request:
    branches: [ main ]
    paths:
      - 'cmd/tofu/ai.go'
      - 'internal/ai/**'
      - 'test-ai-command.sh'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build OpenTofu with AI Command
      run: |
        go build -o tofu ./cmd/tofu
        chmod +x ./tofu
    
    - name: Run AI Command Tests
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GITHUB_ACTIONS: true
      run: |
        chmod +x ./test-ai-command.sh
        ./test-ai-command.sh
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: ai-command-test-results
        path: test-results/
